[package]
name = "ffmonitor"
version = "0.2.0"
edition = "2021"

[lib]
name = "ffmonitor"

[dependencies]
log = "0.4.22"

[[example]]
name = "polling"

[[example]]
name = "callback"

[dev-dependencies]
env_logger = "0.11.5"
