[package]
name = "ffmonitor"
version = "1.0.0"
edition = "2021"

[lib]
name = "ffmonitor"

[dependencies]
log = "0.4.22"
regex = "1.11.1"

[[example]]
name = "polling"

[[example]]
name = "callback"

[dev-dependencies]
env_logger = "0.11.5"
